export const NICHE_QUERIES: Record<string, string[]> = {
  skool_owners: [
    'site:instagram.com "skool" "community" "owner" OR "founder"',
    'site:instagram.com "skool" "helping entrepreneurs" OR "my community"',
    'site:instagram.com "skool" "join my" OR "free community" business',
    'site:instagram.com "skool.com" "coach" OR "mentor"',
    'site:instagram.com "skool" "members" OR "students" entrepreneurship',
    'site:instagram.com "community owner" "business funding" OR "startup"',
  ],
  course_creators: [
    'site:instagram.com "course creator" OR "online course" "students"',
    'site:instagram.com "digital course" "enroll" OR "sign up" coaching',
    'site:instagram.com "my course" "helping" OR "teaching" entrepreneur',
    'site:instagram.com "course launch" OR "program" "DM me" business',
    'site:instagram.com "online education" "founder" OR "creator" coaching',
  ],
  biz_coaches: [
    'site:instagram.com "business coach" OR "biz coach" "helping" OR "DM me"',
    'site:instagram.com "business mentor" "entrepreneur" OR "founder" coaching',
    'site:instagram.com "coaching business" "clients" OR "results" growth',
    'site:instagram.com "business strategy" "coach" OR "consultant" helping',
    'site:instagram.com "mindset coach" "business owner" OR "entrepreneur"',
  ],
  fitness: [
    'site:instagram.com "fitness coach" OR "personal trainer" "online coaching"',
    'site:instagram.com "fitness business" "owner" OR "founder" training',
    'site:instagram.com "online fitness" "coaching" OR "program" clients',
    'site:instagram.com "gym owner" OR "fitness studio" "entrepreneur"',
    'site:instagram.com "health coach" "business" OR "brand" fitness',
  ],
  ecommerce: [
    'site:instagram.com "ecommerce" OR "shopify" "store owner" OR "brand"',
    'site:instagram.com "online store" "founder" OR "CEO" ecommerce',
    'site:instagram.com "dropshipping" OR "amazon fba" "entrepreneur" business',
    'site:instagram.com "ecom brand" "launched" OR "scaling" OR "growing"',
    'site:instagram.com "shopify store" "revenue" OR "sales" founder',
  ],
  real_estate: [
    'site:instagram.com "real estate investor" OR "realtor" "deals" OR "properties"',
    'site:instagram.com "real estate" "flip" OR "wholesale" investor',
    'site:instagram.com "property investor" "portfolio" OR "passive income"',
    'site:instagram.com "real estate agent" "entrepreneur" OR "business owner"',
    'site:instagram.com "real estate mentor" OR "coach" investing',
  ],
  agency_owners: [
    'site:instagram.com "agency owner" OR "marketing agency" "founder"',
    'site:instagram.com "digital agency" "CEO" OR "founder" clients',
    'site:instagram.com "SMMA" OR "social media agency" entrepreneur',
    'site:instagram.com "creative agency" "owner" OR "started" business',
    'site:instagram.com "agency founder" "scaling" OR "growing" marketing',
  ],
  small_biz: [
    'site:instagram.com "small business" "owner" OR "founder" "local"',
    'site:instagram.com "small business owner" "entrepreneur" OR "startup"',
    'site:instagram.com "local business" "launched" OR "opened" owner',
    'site:instagram.com "business owner" "handmade" OR "homemade" OR "local"',
    'site:instagram.com "small biz" "shop" OR "store" owner',
  ],
  trades: [
    'site:instagram.com "contractor" OR "electrician" OR "plumber" "business"',
    'site:instagram.com "HVAC" OR "roofing" "business owner" OR "company"',
    'site:instagram.com "construction" "founder" OR "owner" contractor',
    'site:instagram.com "trades business" "entrepreneur" OR "started"',
    'site:instagram.com "landscaping" OR "painting" business owner',
  ],
  manufacturing: [
    'site:instagram.com "manufacturer" OR "manufacturing" "founder" OR "CEO"',
    'site:instagram.com "factory" OR "production" "owner" OR "entrepreneur"',
    'site:instagram.com "made in USA" "founder" OR "brand" manufacturing',
    'site:instagram.com "manufacturing business" "started" OR "launched"',
    'site:instagram.com "product manufacturer" "entrepreneur" OR "small business"',
  ],
};

export const NICHE_LABELS: Record<string, string> = {
  skool_owners: 'Skool Owners',
  course_creators: 'Course Creators',
  biz_coaches: 'Biz Coaches',
  fitness: 'Fitness',
  ecommerce: 'Ecom',
  real_estate: 'Real Estate',
  agency_owners: 'Agency Owners',
  small_biz: 'Small Biz',
  trades: 'Trades',
  manufacturing: 'Manufacturing',
};
